### ISSUE TITLE
Not Executable

### ISSUE THREAD

**Issue by ghost** [jonas-koeritz/actioncam#11]
Hallo @jonas-koeritz
(Ich habe gesehen, dass du aus Hamburg kommst, deshab schreibe ich auf Deutsch)
Wenn ich den Befehl `go run actioncam.go 192.168.100.1` ausführe, kommen folgende Fehlermeldungen
`actioncam.go:19:2: no required module provides package github.com/jonas-koeritz/actioncam/libipcamera: go.mod file not found in current directory or any parent directory; see 'go help modules'
actioncam.go:20:2: no required module provides package github.com/jonas-koeritz/actioncam/rtsp: go.mod file not found in current directory or any parent directory; see 'go help modules'
actioncam.go:21:2: no required module provides package github.com/spf13/cobra: go.mod file not found in current directory or any parent directory; see 'go help modules'`.
Ich verstehe nicht, wie ich den fehler beheben soll. Vielen Dank.

**Comment by jonas-koeritz** [comment]
Moin!

Den Code habe ich selbst lange nicht benutzt, das Problem ist aber dass die Anwendung noch nicht auf die "neuen" Go modules angepasst ist (glaube ich). Schaue ich mir nachher mal an und aktualisiere das hier entsprechend.

Viele Grüße

**Comment by nico663** [comment]
Okay, vielen Dank für die sehr schnelle Antwort. 😃 Wenn du den Code aktualisiert hast, könntest du das dann hier im Thread schreibenß Danke

Tschüss

**Comment by jonas-koeritz** [comment]
Anpassung ist erledigt, go get / go install etc. sollten jetzt wieder damit klarkommen.

**Comment by nico663** [comment]
Vielen Dank
