### ISSUE TITLE
Last Issue Follow-up

### ISSUE THREAD

**Issue by mattigins** [jonas-koeritz/actioncam#5]
Any chance you could work with me to get your nodeJS code working for me?

The problem is that i do not know GO and i want to use the node version to shove in an android app.

**Comment by jonas-koeritz** [comment]
Please try the go version first to verify that your camera is indeed compatible. I could help you implement the protocol in Java for your Android App too.

**Comment by mattigins** [comment]
The GO version does certainly work flawlessly.

**Comment by mattigins** [comment]
Update: I was able to get the node version working but i have to go back to a previous version with the buffer. However now i get a buffer. 6 secs in ffplay and 2 in vlc. Advise?

**Comment by BlueNalgene** [comment]
This is expected behavior, @mattigins. The buffer reduction code was developed in the Go version.  In the Nodejs version, @jonas-koeritz has not addressed the buffering issue.  This is one of the reasons the Go version is recommended right now.

**Comment by jonas-koeritz** [comment]
@mattigins, have you tried mplayer to play the stream? See the readme for details.
