### ISSUE TITLE
After disconnecting from RTSP server, for loop inside handleCameraStream in RTPRelay.go keeps running

### ISSUE THREAD

**Issue by fildaw** [jonas-koeritz/actioncam#6]
Just like in the title, after disconnecting from RTSP server, _for_ loop in `handleCameraStream` keeps running and causing memory leaks and high CPU usage.
I found that the _if_ statement responsible for breaking this loop never executes (even after executing `Stop` function). Also `break` instruction in this _if_ statement isn't actually pointing to loop, but to the `select` statement.

I've solved this issue using global variable _close_ inside RTPRelay.go and setting it to false in `CreateRTPRelay` and to true in `Stop`. Also _if_ responsible for closing rtp relay now checks for value of this global variable.

According to problem with `break` I found a workaround using labels (like this: https://stackoverflow.com/questions/11104085/in-go-does-a-break-statement-break-from-a-switch-select)

I'm not familiar with golang, so maybe my 'fixes' are not good, but as I tested your app with this modifications it worked nice.

P.S I'm using golang 1.12 on Ubuntu 16.04. (I tested it also on golang 1.13 and the same issue persist)
P.P.S. Your job done with reverse engineering of camera's protocol is awesome and I really admire it. Thanks to your app and post on your blog, I'm able to use my camera as regular IP camera.

**Comment by jonas-koeritz** [comment]
Hi @fildaw thanks for opening an issue! I do not use this code very much on my own so real-world testing is mostly done by users. Your proposal seems fine to me, you can create a pull
