### ISSUE TITLE
RTSP - Features, Stream is not smooth

### ISSUE THREAD

**Issue by mlinton** [jonas-koeritz/actioncam#8]
Hi thanks again for your work on the app to connect to these cameras.  I noticed that there may be an option to enable the busybox ssh shell on the camera and enable the RTSP server locally from the camera?  is this possible?

Also the RTSP stream from the go application is really laggy with the video and appears to crash often.  Any updates to why this is?

Thanks again.

![image](https://user-images.githubusercontent.com/2158650/78722007-d4b99f00-78e5-11ea-9a1b-20c6aee59391.png)

**Comment by jonas-koeritz** [comment]
I haven't experienced a laggy stream or packet loss with my camera and network connection (like your MPlayer console suggests). If there is an RTSP Server on the camera it could be enabled remotely, but as far as I can tell there is none (the manufacturers app preview doesn't use RTSP).
Have you tried the RTP stream too? Can you rule out network connectivity issues?

**Comment by jonas-koeritz** [comment]
I also planned to reimplement the RTSP part, this wouldn't change much on how the raw video stream is submitted to the player though.

**Comment by mlinton** [comment]
Yeah for some reason the video lags, while in the XVD app the stream is quite smooth and fluid.

**Comment by jonas-koeritz** [comment]
Can you provide me with a packet capture? Just use Wireshark to record
everything that's going on during the laggy video transmission.

mlinton <notifications@github.com> schrieb am Di., 14. Apr. 2020, 20:06:

**Comment by jonas-koeritz** [comment]
No response, please reopen if still interested.
