### ISSUE TITLE
How to make it work

### ISSUE THREAD

**Issue by DaniGarciaLopez** [jonas-koeritz/actioncam#9]
Hello!

I'm not familiar with go lang nor rtsp connection so probably I'm doing things wrong. My camera is an Eken H8R so I'm not sure if it is completely compatible with your program either.

I managed to install go and your library in my raspberry pi. I can access to my camera stream with the following command: mplayer -nocache rtsp://192.168.1.1/MJPG

I am not sure how to execute the command to start RTSP server. I tried: go run actioncam.go 192.168.1.1, but it showed error connection refused.

I don't know if I'm doing it in a good way or it is just that my camera is not compatible. Any further help is welcome. Thanks!

**Comment by jonas-koeritz** [comment]
Hi,
the first thing I noticed is that you got the IP-Adresses mixed up.

My tool connects to the camera, so actioncam.....<Camera IP> is the correct command (if your camera supports the discovery feature you could even omit the camera IP).

Step two is viewing the RTSP using mplay, the RTSP Server is my application, so the RTSP URL should contain your PCs IP-Address or simply localhost/127.0.0.1

If the tool isn't able to find the camera or connect at all, let me know and I will have a look if it is incompatible.

**Comment by DaniGarciaLopez** [comment]
Thanks for the help!

Writting "actioncam" in terminal shows me the following error: bash: actioncam: command not found

Probably I did something wrong installing go or your library. These are the steps I followed:

wget https://storage.googleapis.com/golang/go1.10.1.linux-armv6l.tar.gz
sudo tar -C /usr/local -xvf go1.10.1.linux-armv6l.tar.gz
PATH=$PATH:/usr/local/go/bin
. ~/.profile
rm go1.10.1.linux-armv6l.tar.gz
go get github.com/jonas-koeritz/actioncam

The library is located in:
~/go/src/github.com/jonas-koeritz/actioncam

**Comment by jonas-koeritz** [comment]
Go to the folder and run "go build ."

The binary is in the current directory so "./actioncam" should be correct.

**Comment by jonas-koeritz** [comment]
Using "go run" is okay too, it shouldn't make a difference.

**Comment by DaniGarciaLopez** [comment]
I built the folder and now command "./actioncam" works.

If I dont add IP it shows: "cannot create camera without IP-Address". I tried:
`./actioncam 127.0.0.1` 
`./actioncam 192.168.1.1` 

Both show connection refused error. How can I know the IP of my camera?

**Comment by jonas-koeritz** [comment]
Looks like it might not be compatible if it didn't find it automatically. I'll have a look at your camera and get back to you soon!

**Comment by jonas-koeritz** [comment]
Is your PC connected to your cameras wifi?

**Comment by DaniGarciaLopez** [comment]
Yes. Using the following command I have access to video stream:
`mplayer -nocache rtsp://192.168.1.1/MJPG`
![2020-05-15-214239_1920x1080_scrot](https://user-images.githubusercontent.com/22426909/82093100-c0459f00-96fa-11ea-87e3-2754becc8332.png)

A lot of packages are missed, it shows me every 3-4 seconds a new frame. Anyway, this doesnt bother me because I want to use your library just to take pictures and download them.

**Comment by jonas-koeritz** [comment]
If your camera already does MJPEG streaming it might be totally incompatible. The cameras I've worked with don't do live streaming via a standard protocol at all. That's why I created the library in the first place.

I can have a look at the default app and see if I can implement the file management stuff for your cam as well.

**Comment by DaniGarciaLopez** [comment]
I understand. If you can it would be great!

This post talks about the protocol that my camera uses, it might help you:
http://hackeken.blogspot.com/2017/01/reverse-engineering-eken-android-app.html

**Comment by DaniGarciaLopez** [comment]
Hello again Jonas! Im back with the project and I would like to use your library. Did you have time to check compatibility with Eken H8? If not I was planning to buy one of the cameras you said it is compatible, but I was trying to buy either campark or tectectec and they are not currently available in amazon. Do you have any idea of which available cameras are still compatible with your library? Thanks!

**Comment by jonas-koeritz** [comment]
The Xpro broke a few weeks ago and I invested in a GoPro Hero 5 as replacement.
If you choose any camera and tell me which app it uses natively I could have a look at it and tell if it would possibly be supported.

**Comment by DaniGarciaLopez** [comment]
I was planning to buy Victure AC700. It uses this app: https://play.google.com/store/apps/details?id=com.dlk.IPCamViewer

**Comment by jonas-koeritz** [comment]
On first glance this doesn't look like it would use the same library. If
you buy on Amazon you could send it back as not fitting the intended
purpose 😉

Am Mo., 20. Juli 2020 um 12:43 Uhr schrieb dgarcialopez <
notifications@github.com>:

**Comment by DaniGarciaLopez** [comment]
Yes hahahaha Campark X20 uses CamKing app, it should work right?

**Comment by DaniGarciaLopez** [comment]
Hi! I bought and tried Campark X5 and seems that is not compatible. IP error appears ("cannot create camera without IP-Address"). How could I know which cameras might be compatible? Thanks!

**Comment by jonas-koeritz** [comment]
Did you connect to the cameras network? This looks just like the auto
discovery didn't work.

dgarcialopez <notifications@github.com> schrieb am Do., 30. Juli 2020,
18:34:

**Comment by DaniGarciaLopez** [comment]
Yes, it is connected. I tried also using these IPs and it does not work:
`./actioncam 127.0.0.1`
`./actioncam 192.168.1.1`

**Comment by jonas-koeritz** [comment]
You need to use the IP-Address of the camera, 127.0.0.1 is your own
computer, the camera usually gives itself the .100 or another address on
its own wifi. You can use Wireshark to see who's talking on the network.

dgarcialopez <notifications@github.com> schrieb am Do., 30. Juli 2020,
19:39:

**Comment by DaniGarciaLopez** [comment]
I checked with Wireshark and looks like the IP is: 192.72.1.100. But I tried with that IP and it is not working either

**Comment by jonas-koeritz** [comment]
I will have a look at the cameras native app tomorrow and try to determine
if it should be working.

dgarcialopez <notifications@github.com> schrieb am Do., 30. Juli 2020,
20:27:

**Comment by DaniGarciaLopez** [comment]
Great! Thanks again :)

**Comment by jonas-koeritz** [comment]
Doesn't look like this will be easily implementable. Closing for now.
